### ISSUE TITLE
Unable to create migration script

### ISSUE THREAD

**Issue by truthz03** [win7user10/Laraue.EfCoreTriggers#112]
Hi,

I'm using Net8 with Laraue.EfCoreTriggers.SqlServer 8.1.2

if I create my code first migration script with `Add-Migration AddTrigger -OutputDir Migrations -verbose` the first time including triggers, everyting is working.

But if I create my first migration script without triggers, add 
```
modelBuilder.Entity<ObjectsecurityAttachmentModel>()
    .AfterDelete(trigger => trigger
        .Action(action => action
            .Delete<FileDataModel>((e, a) => e.Old.FileId == a.Id)));
```
after that und create a second step migration script I get the following error:

> System.InvalidOperationException: DbSet<System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]> should be added to the DbContext
>    at Laraue.EfCoreTriggers.Common.SqlGeneration.EfCoreDbSchemaRetriever.GetEntityType(Type type)
>    at Laraue.EfCoreTriggers.Common.SqlGeneration.EfCoreDbSchemaRetriever.GetTableSchemaName(Type entity)
>    at Laraue.EfCoreTriggers.Common.SqlGeneration.SqlGenerator.GetSchemaPrefixSql(Type entity)
>    at Laraue.EfCoreTriggers.SqlServer.SqlServerTriggerVisitor.GenerateDeleteTriggerSql(String triggerName, IEntityType entityType)
>    at Laraue.EfCoreTriggers.Common.Migrations.MigrationsExtensions.AddDeleteTriggerSqlMigration(ITriggerVisitor triggerVisitor, IList`1 list, IAnnotation annotation, IEntityType entityType)
>    at Laraue.EfCoreTriggers.Common.Migrations.TriggerModelDiffer.AddTriggerOperations(IEnumerable`1 operations, IRelationalModel source, IRelationalModel target)
>    at Laraue.EfCoreTriggers.Common.Migrations.MigrationsModelDiffer.GetDifferences(IRelationalModel source, IRelationalModel target)
>    at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace, String language)
>    at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
>    at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
>    at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
>    at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
>    at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)

Did I do anything wrong? Isn't it possible to add triggers after already having other migration scripts?

**Comment by win7user10** [comment]
Hi. Could you please provide the `ObjectsecurityAttachmentModel `definition to repoduce the case?

**Comment by ejsmith** [comment]
I'm getting the same issue as well. Any ideas?

**Comment by SpeedyCraftah** [comment]
> I'm getting the same issue as well. Any ideas?
Same problem. I'm not too familiar with C# so I'm not sure what the issue could be here, but sadly it looks like I have to drop this library for the time being as it is not working with basic EFCore schemas. For the time being I think the best workaround here will be to execute a raw SQL statement which creates the triggers. It's not an ideal workaround, but it's probably the closest you can get to "triggers with ORM in C#".
For some reason, triggers aren't very popular in the C# ORM world, or just the ORM world in general. I think it's because most applications exclusively use a single database and aren't spread across services, so if you wanted something along the lines of a "trigger", you'd simply override one of the insert functions or something similar on one of the schemas to do something, then proceed, instead of doing something that EFCore might not be aware of.

**Comment by joecons97** [comment]
Hi all, just came across a similar issue. As anyone come across a fix for this?
