### ISSUE TITLE
System.NullReferenceException: 'Object reference not set to an instance of an object.'

### ISSUE THREAD

**Issue by mehmet-erdogdu** [win7user10/Laraue.EfCoreTriggers#7]
modelBuilder.Entity<BlogPosts>()
                .AfterUpdate(trigger => trigger
                .Action(action => action
                .Condition((oldTransaction, newTransaction) => oldTransaction.ViewCount + 1 == newTransaction.ViewCount)
                .Update<Users>(
                (oldTransaction, updatedTransaction, user) => user.Guid == oldTransaction.CreatedBy,
                (oldTransaction, updatedTransaction, user) => new Users { BlogPostViewCount = user.BlogPostViewCount + 1 })))

  at Microsoft.EntityFrameworkCore.RelationalEntityTypeExtensions.GetTableName(IEntityType entityType)
   at Laraue.EfCoreTriggers.Common.Builders.Providers.BaseExpressionProvider.GetTableName(Type entity)
   at Laraue.EfCoreTriggers.Common.Builders.Providers.BaseExpressionProvider.GetTableName(MemberInfo memberInfo)
   at Laraue.EfCoreTriggers.Common.Builders.Providers.BaseExpressionProvider.GetMemberExpressionSql(MemberExpression memberExpression, ArgumentType argumentType)
   at Laraue.EfCoreTriggers.Common.Builders.Providers.BaseExpressionProvider.GetMemberExpressionSql(MemberExpression memberExpression, Dictionary`2 argumentTypes)
   at Laraue.EfCoreTriggers.Common.Builders.Providers.BaseExpressionProvider.GetUnaryExpressionSql(UnaryExpression unaryExpression, Dictionary`2 argumentTypes)
   at Laraue.EfCoreTriggers.Common.Builders.Providers.BaseExpressionProvider.GetExpressionSql(Expression expression, Dictionary`2 argumentTypes)
   at Laraue.EfCoreTriggers.Common.Builders.Providers.BaseExpressionProvider.<>c__DisplayClass39_0.<GetBinaryExpressionSql>b__1(Expression part)
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at Laraue.EfCoreTriggers.Common.Builders.Providers.SqlBuilder.MergeColumnsInfo(IEnumerable`1 generatedSqls)
   at Laraue.EfCoreTriggers.Common.Builders.Providers.SqlBuilder..ctor(IEnumerable`1 generatedSqls)
   at Laraue.EfCoreTriggers.Common.Builders.Providers.BaseExpressionProvider.GetBinaryExpressionSql(BinaryExpression binaryExpression, Dictionary`2 argumentTypes)
   at Laraue.EfCoreTriggers.Common.Builders.Providers.BaseTriggerProvider.GetConditionStatementSql(LambdaExpression conditionExpression, Dictionary`2 argumentTypees)
   at Laraue.EfCoreTriggers.Common.Builders.Providers.BaseTriggerProvider.GetTriggerUpdateActionSql[TTriggerEntity,TUpdateEntity](TriggerUpdateAction`2 triggerUpdateAction)
   at Laraue.EfCoreTriggers.Common.Builders.Triggers.Base.TriggerUpdateAction`2.BuildSql(ITriggerProvider visitor)
   at Laraue.EfCoreTriggers.Common.Builders.Providers.MySqlProvider.<GetTriggerActionsSql>b__11_0[TTriggerEntity](ITriggerAction action)
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at Laraue.EfCoreTriggers.Common.Builders.Providers.SqlBuilder.MergeColumnsInfo(IEnumerable`1 generatedSqls)
   at Laraue.EfCoreTriggers.Common.Builders.Providers.MySqlProvider.GetTriggerActionsSql[TTriggerEntity](TriggerActions`1 triggerActions)
   at Laraue.EfCoreTriggers.Common.Builders.Triggers.Base.TriggerActions`1.BuildSql(ITriggerProvider visitor)
   at Laraue.EfCoreTriggers.Common.Builders.Providers.MySqlProvider.<GetTriggerSql>b__12_0[TTriggerEntity](ISqlConvertible action)
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at Laraue.EfCoreTriggers.Common.Builders.Providers.SqlBuilder.MergeColumnsInfo(IEnumerable`1 generatedSqls)
   at Laraue.EfCoreTriggers.Common.Builders.Providers.SqlBuilder..ctor(IEnumerable`1 generatedSqls)
   at Laraue.EfCoreTriggers.Common.Builders.Providers.MySqlProvider.GetTriggerSql[TTriggerEntity](Trigger`1 trigger)
   at Laraue.EfCoreTriggers.Common.Builders.Triggers.Base.Trigger`1.BuildSql(ITriggerProvider visitor)
   at Laraue.EfCoreTriggers.Extensions.EntityTypeBuilderExtensions.AddTriggerAnnotation[T](EntityTypeBuilder`1 entityTypeBuilder, Trigger`1 configuredTrigger)
   at Laraue.EfCoreTriggers.Extensions.EntityTypeBuilderExtensions.AddOnUpdateTrigger[T](EntityTypeBuilder`1 entityTypeBuilder, Action`1 configuration, TriggerTime triggerTime)
   at Laraue.EfCoreTriggers.Extensions.EntityTypeBuilderExtensions.AfterUpdate[T](EntityTypeBuilder`1 entityTypeBuilder, Action`1 configuration)

**Comment by win7user10** [comment]
Hi, @mehmet-erdogdu, looks like the entity doesn't contain information about table name, could you please provide your Users and Transactions models code to reproduce the issue?

**Comment by rekosko** [comment]
I'm having the same issue. What do you mean that entity doesn't contain information about table name? All I can think about is to specify e.g.: `builder.ToTable("TableName");` Is there something else that you have in mind?

**Comment by portno** [comment]
Hi,

the issue seems to appear when using inheritance. Consider this example:
```
public abstract class BaseModel
{
    public Guid Id { get; set; }
}
public class Product: BaseModel
{
    // ...
}
```
and in DbContext:
```
public DbSet<Product> Products { get; set; }
```
and somewhere in your trigger use `... , product) => product.Id === ...)`.
`GetColumnName(MemberInfo memberInfo)` gets the MemberInfo of that expression which has `BaseModel` as `DeclaringType` and not `Product` which is the type that is used  as a table.

Adding `.Entity<BaseModel>().ToTable("Whatever")` can cause other issues if you did not intend `ModelBase` to be a table.

**Comment by Meberem** [comment]
@portno I encountered this today with a slightly more complex setup. In my case, the base model had not been configured before the Trigger configuration runs on the builder. A simple hack that worked for me was changing the order of my `IEntityTypeConfiguration<TType>` from:

```
public class MyTypeConfiguration : IEntityTypeConfiguration<BaseModel>, IEntityTypeConfiguration<Product>
{
    public void Configure(EntityTypeBuilder<BaseModel> builder)
	{
         builder.AfterInsert(....);
    }

    public void Configure(EntityTypeBuilder<Product> builder)
	{
    }
}
```


```
public class MyTypeConfiguration : IEntityTypeConfiguration<Product>, IEntityTypeConfiguration<BaseModel>
{
    public void Configure(EntityTypeBuilder<BaseModel> builder)
	{
         builder.AfterInsert(....);
    }

    public void Configure(EntityTypeBuilder<Product> builder)
	{
    }
}
```
I don't know if that will work for you, or what the root cause is just yet, but it might help
