### ISSUE TITLE
postgresql trigger/function name

### ISSUE THREAD

**Issue by Klynk** [win7user10/Laraue.EfCoreTriggers#79]
There are quotes on the trigger function create statement, and no quotes on the drop statement.

This causes subsequent Up migrations to fail, as the trigger/function cannot be found when dropped.
This is the case for the Down as well.

![image](https://user-images.githubusercontent.com/28676303/221611983-276675e7-b44e-4ecb-8d19-48449fe9da76.png)

Laraue.EfCoreTriggers.Common: 7.0.4 (also tested on 7.0.3 - 7.0.0)
Laraue.EfCoreTriggers.PostgreSql: 7.0.4 (also tested on 7.0.3 - 7.0.0)

**Comment by win7user10** [comment]
Hi, I made a fix in version 7.0.5, it should work

**Comment by win7user10** [comment]
@Klynk I made a fix yesterday, hope it will work

**Comment by Klynk** [comment]
Thank you for the response. I am still having the same issue after the update.
I made a smaller project which reproduces the issue for me.

[MigrationBug.zip](https://github.com/win7user10/Laraue.EfCoreTriggers/files/10866582/MigrationBug.zip)

When I run `add-migration 2` I get the following error with 7.0.6:

```SH
PM> add-migration 2
Build started...
Build succeeded.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.RelationalEntityTypeExtensions.GetTableName(IReadOnlyEntityType entityType)
   at Microsoft.EntityFrameworkCore.RelationalEntityTypeExtensions.GetSchema(IReadOnlyEntityType entityType)
   at Laraue.EfCoreTriggers.Common.Services.Impl.EfCoreDbSchemaRetriever.GetTableSchemaName(Type entity)
   at Laraue.EfCoreTriggers.Common.Services.Impl.SqlGenerator.GetFunctionNameSql(Type entity, String name)
   at Laraue.EfCoreTriggers.PostgreSql.PostgreSqlTriggerVisitor.GenerateDeleteTriggerSql(String triggerName, IEntityType entityType)
   at Laraue.EfCoreTriggers.Common.Migrations.MigrationsExtensions.AddDeleteTriggerSqlMigration(ITriggerVisitor triggerVisitor, IList`1 list, IAnnotation annotation, IEntityType entityType)
   at Laraue.EfCoreTriggers.Common.Migrations.TriggerModelDiffer.AddTriggerOperations(IEnumerable`1 operations, IRelationalModel source, IRelationalModel target)
   at Laraue.EfCoreTriggers.Common.Migrations.MigrationsModelDiffer.GetDifferences(IRelationalModel source, IRelationalModel target)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace, String language)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Object reference not set to an instance of an object.
```

**Comment by win7user10** [comment]
@Klynk just released another version

**Comment by Klynk** [comment]
@win7user10 I tested version 7.0.7 and it works as expected now. Thank you for your help 🎉
