### ISSUE TITLE
Support net8

### ISSUE THREAD

**Issue by stanislav-a-frolov** [win7user10/Laraue.EfCoreTriggers#91]
Hi, everyone!

While using Laraue.EfCoreTriggers.PostgreSql version 7.1.1 with net8, I encounter the following error while creating ef model. After I rebuild package for net8 by changing net7.0 to net8.0 everything is fine.

```Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.MissingMethodException: Method not found: 'Microsoft.EntityFrameworkCore.Metadata.IMutableModel Microsoft.EntityFrameworkCore.Metadata.IMutableEntityType.get_Model()'.
   at Laraue.EfCoreTriggers.Common.Extensions.EntityTypeBuilderExtensions.AddTriggerAnnotation[T](EntityTypeBuilder`1 entityTypeBuilder, ITrigger configuredTrigger)
   at Laraue.EfCoreTriggers.Common.Extensions.EntityTypeBuilderExtensions.AddTrigger[T,TRefs](EntityTypeBuilder`1 entityTypeBuilder, TriggerEvent triggerEvent, TriggerTime triggerTime, Action`1 configureTrigger)
   at Laraue.EfCoreTriggers.Common.Extensions.EntityTypeBuilderExtensions.AfterDelete[T](EntityTypeBuilder`1 entityTypeBuilder, Action`1 configuration)```

**Comment by buraktamturk** [comment]
Sounds like this action did not publish the 8.0.0 release:
https://github.com/win7user10/Laraue.EfCoreTriggers/actions/runs/6881326638/job/18739835843

Maybe @win7user10 help?

**Comment by win7user10** [comment]
It should be available now
